version: '3'

services:
  php8.2:
    build:
      context: ./docker/php8.2
    hostname: php8.2
    ports:
      - 10002:9000
    volumes:
      - ./projects/:/var/www/html
      - ./docker/php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf 
      - ./docker/php8.2/php.ini:/usr/local/etc/php/php.ini 
    environment:
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
  
  php7.4:
    build:
      context: ./docker/php7.4
    hostname: php7.4
    ports:
      - 10001:9000
    volumes:
      - ./projects/:/var/www/html
      - ./docker/php7.4/www.conf:/usr/local/etc/php-fpm.d/www.conf 
      - ./docker/php7.4/php.ini:/usr/local/etc/php/php.ini 
    environment:
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 

  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - :80 
      - :8000
      - :8888
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2
      - php7.4

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - :80